resource_types:
- name: ubuntu
  type: docker-image
  source:
    repository: ubuntu

resources:
- name: uname-repo
  type: git
  source:
    uri: https://github.com/matthewfischer/uname.git
    branch: master

jobs:
- name: uname
  plan:
  - get: ubuntu
  - task: uname-a
    file: uname-repo/tasks/uname.yml
